name = "Dino Run Blink"
url = "https://github.com/deanzahci/dino-run-blink"
published = 2025-06-01T00:00:00Z
description = "Play the classic dino run game with eye blinks by processing EOG from Brain-Computer Interface in realtime"
type = "hardware"
oss = true
