name = "OpenCode BTCA"
mainUrl = "https://github.com/koichincom/opencode-btca"
published = 2025-06-01T00:00:00Z
description = "Allow OpenCode to directly get infomation from the tool's source code by integrating Better Context CLI"
pinned = true
featured = true
