name = "Personal Website"
url = "https://github.com/koichincom/website"
published = 2025-06-01T00:00:00Z
description = "My personal website, designed to a minimal and calm space for sharing my thoughts and projects."
pinned = false
featured = false
