name = "Signify ASL"
url = "https://signifyasl.com"
published = 2027-06-01T00:00:00Z
description = "Gamify your American-sign language learning using a custom LSTM model. Think Wordle and MonkeyType but for learning sign language. Available on signifyasl.com."
type = "tryOut"
oss = true
