name = "Signify"
url = "https://github.com/deanzahci/signify"
published = 2027-06-01T00:00:00Z
description = "Gamify sign language learning with fast and lightweight Computer Vision model, trained from scratch"
