name = "Still Waiting"
mainUrl = "https://github.com/koichincom/still-waiting"
published = 2027-06-01T00:00:00Z
description = "24h reply reminder bot for Discord. Free to add & self-hostable."
pinned = true
featured = true
