name = "Still Waiting"
url = "https://github.com/koichincom/still-waiting"
published = 2027-06-01T00:00:00Z
description = "24 hours reply reminder bot for Discord. Free to add and self-hostable."
pinned = true
featured = true
